"""
Module 6 (Bonus) — PDF Report Generator
Produces a downloadable one-page PDF summary using ReportLab.
"""

import io
import logging
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

logger = logging.getLogger(__name__)

# Brand colours
GREEN  = colors.HexColor("#22c55e")
AMBER  = colors.HexColor("#f59e0b")
RED    = colors.HexColor("#ef4444")
DARK   = colors.HexColor("#1e293b")
LIGHT  = colors.HexColor("#f1f5f9")
WHITE  = colors.white


def _score_color(score: int):
    if score >= 75:
        return GREEN
    if score >= 50:
        return AMBER
    return RED


def generate_pdf_report(analysis: dict, scoring: dict, ats_checks: list) -> bytes:
    """
    Build and return a PDF report as bytes.
    """
    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm,   bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    story  = []

    # ── Title ──────────────────────────────────
    title_style = ParagraphStyle(
        "title", parent=styles["Title"],
        textColor=DARK, fontSize=22, spaceAfter=4
    )
    sub_style = ParagraphStyle(
        "sub", parent=styles["Normal"],
        textColor=colors.HexColor("#64748b"), fontSize=10, spaceAfter=16
    )
    story.append(Paragraph("Resume Analysis Report", title_style))
    story.append(Paragraph("Generated by AI Resume Analyzer", sub_style))
    story.append(HRFlowable(width="100%", thickness=1, color=LIGHT))
    story.append(Spacer(1, 0.4*cm))

    # ── Score Banner ────────────────────────────
    score      = scoring["final_score"]
    score_col  = _score_color(score)
    grade      = scoring["grade"]

    # Define a custom style for the big score to ensure baseline alignment
    score_style = ParagraphStyle(
        "score_style", parent=styles["Normal"],
        fontSize=36, leading=40, textColor=score_col
    )
    
    score_data = [
        [
            Paragraph(f'<b>{score}</b><font size="14">/100</font>', score_style),
            Paragraph(f'<b>Grade:</b> {grade}<br/>'
                      f'<b>AI Score:</b> {scoring["ai_score"]}/100<br/>'
                      f'<b>Keyword Score:</b> {scoring["keyword_score"]}/100',
                      styles["Normal"]),
        ]
    ]
    score_table = Table(score_data, colWidths=[6*cm, 10*cm])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT),
        ("ROUNDEDCORNERS", [8]),
        ("TOPPADDING",    (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.5*cm))

    # ── Summary ─────────────────────────────────
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=DARK, spaceBefore=10, spaceAfter=4)
    story.append(Paragraph("AI Summary", h2))
    story.append(Paragraph(analysis.get("summary", "N/A"), styles["Normal"]))
    story.append(Spacer(1, 0.4*cm))

    # ── Skills Side by Side ──────────────────────
    found   = analysis.get("found_skills", [])
    missing = analysis.get("missing_skills", [])

    found_text   = "<br/>".join(f"✓ {s}" for s in found)   or "None identified."
    missing_text = "<br/>".join(f"✗ {s}" for s in missing) or "None — great fit!"

    skills_data = [[
        Paragraph(f"<b><font color='#22c55e'>Found Skills</font></b><br/>{found_text}",   styles["Normal"]),
        Paragraph(f"<b><font color='#ef4444'>Missing Skills</font></b><br/>{missing_text}", styles["Normal"]),
    ]]
    skills_table = Table(skills_data, colWidths=[8.5*cm, 8.5*cm])
    skills_table.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("LINEAFTER",     (0, 0), (0, -1), 1, colors.HexColor("#e2e8f0")),
    ]))
    story.append(Paragraph("Skills Breakdown", h2))
    story.append(skills_table)
    story.append(Spacer(1, 0.4*cm))

    # ── Strengths & Weaknesses ──────────────────
    strengths  = analysis.get("strengths", [])
    weaknesses = analysis.get("weaknesses", [])

    if strengths:
        story.append(Paragraph("Strengths", h2))
        for s in strengths:
            story.append(Paragraph(f"• {s}", styles["Normal"]))
        story.append(Spacer(1, 0.3*cm))

    if weaknesses:
        story.append(Paragraph("Areas for Improvement", h2))
        for w in weaknesses:
            story.append(Paragraph(f"• {w}", styles["Normal"]))
        story.append(Spacer(1, 0.3*cm))

    # ── ATS Checks ──────────────────────────────
    story.append(Paragraph("ATS Checklist", h2))
    ats_data = [["Check", "Status", "Detail"]]
    for c in ats_checks:
        status = "✓ Pass" if c["passed"] else "✗ Fail"
        col    = GREEN if c["passed"] else RED
        ats_data.append([
            c["check"],
            Paragraph(f'<font color="{col.hexval()}"><b>{status}</b></font>', styles["Normal"]),
            c["message"],
        ])

    ats_table = Table(ats_data, colWidths=[5.1*cm, 2.55*cm, 9.35*cm])
    ats_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
    ]))
    story.append(ats_table)

    # ── ATS Flags ───────────────────────────────
    ats_flags = analysis.get("ats_flags", [])
    if ats_flags:
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph("AI-Detected ATS Flags", h2))
        for f in ats_flags:
            story.append(Paragraph(f"⚠ {f}", styles["Normal"]))

    doc.build(story)
    return buffer.getvalue()
